// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSConstants
{
        public const string achievement_sturdy = "CgkI7pnK97MREAIQBg"; // <GPGSID>
        public const string achievement_adult_toadler = "CgkI7pnK97MREAIQAw"; // <GPGSID>
        public const string achievement_lucky = "CgkI7pnK97MREAIQCQ"; // <GPGSID>
        public const string achievement_young_toadler = "CgkI7pnK97MREAIQAg"; // <GPGSID>
        public const string achievement_determined = "CgkI7pnK97MREAIQCA"; // <GPGSID>
        public const string leaderboard_high_score = "CgkI7pnK97MREAIQBQ"; // <GPGSID>
        public const string leaderboard_time_for_500 = "CgkI7pnK97MREAIQDA"; // <GPGSID>
        public const string leaderboard_time_for_200 = "CgkI7pnK97MREAIQCw"; // <GPGSID>
        public const string achievement_collector = "CgkI7pnK97MREAIQCg"; // <GPGSID>
        public const string achievement_experienced_toadler = "CgkI7pnK97MREAIQBA"; // <GPGSID>
        public const string achievement_resilient = "CgkI7pnK97MREAIQBw"; // <GPGSID>
        public const string achievement_toddler_toadler = "CgkI7pnK97MREAIQAQ"; // <GPGSID>

}

